# III-IV
# Copyright 2023 Julio Merino

name: Test

on: [push, pull_request]

jobs:
    lint:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        env:
            RUSTC_WRAPPER: "sccache"
            SCCACHE_GHA_ENABLED: "true"
        steps:
            - uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  # Use the latest stable Rust version for lint checks to
                  # verify any new Clippy warnings that may appear.
                  toolchain: stable
                  default: true
                  components: clippy, rustfmt
            - uses: actions/checkout@v4
            - uses: mozilla-actions/sccache-action@v0.0.9
            - run: sudo apt update
            - run: sudo apt install pre-commit
            - run: ./lint.sh

    test-individually:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        env:
            AZURE_MAPS_KEY: ${{ secrets.AZURE_MAPS_KEY }}
            PGSQL_TEST_HOST: ${{ secrets.PGSQL_TEST_HOST }}
            PGSQL_TEST_PORT: ${{ secrets.PGSQL_TEST_PORT }}
            PGSQL_TEST_DATABASE: ${{ secrets.PGSQL_TEST_DATABASE }}
            PGSQL_TEST_USERNAME: ${{ secrets.PGSQL_TEST_USERNAME }}
            PGSQL_TEST_PASSWORD: ${{ secrets.PGSQL_TEST_PASSWORD }}
            RUSTC_WRAPPER: "sccache"
            SCCACHE_GHA_ENABLED: "true"
        steps:
            - uses: actions/checkout@v4
            - uses: mozilla-actions/sccache-action@v0.0.9
            - run: ./test.sh all

    test-workspace:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        env:
            AZURE_MAPS_KEY: ${{ secrets.AZURE_MAPS_KEY }}
            PGSQL_TEST_HOST: ${{ secrets.PGSQL_TEST_HOST }}
            PGSQL_TEST_PORT: ${{ secrets.PGSQL_TEST_PORT }}
            PGSQL_TEST_DATABASE: ${{ secrets.PGSQL_TEST_DATABASE }}
            PGSQL_TEST_USERNAME: ${{ secrets.PGSQL_TEST_USERNAME }}
            PGSQL_TEST_PASSWORD: ${{ secrets.PGSQL_TEST_PASSWORD }}
            RUSTC_WRAPPER: "sccache"
            SCCACHE_GHA_ENABLED: "true"
        steps:
            - uses: actions/checkout@v4
            - uses: mozilla-actions/sccache-action@v0.0.9
            - run: ./test.sh
