# III-IV
# Copyright 2023 Julio Merino

name: Test

on: push

jobs:
    lint:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        env:
            RUSTC_WRAPPER: "sccache"
            SCCACHE_GHA_ENABLED: "true"
        steps:
            - uses: actions/checkout@v4
            - uses: cargo-bins/cargo-binstall@main
            - uses: mozilla-actions/sccache-action@v0.0.9
            - run: sudo apt update
            - run: cargo binstall --no-confirm prek
            - run: prek run --all-files

    check-individually:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        env:
            RUSTC_WRAPPER: "sccache"
            SCCACHE_GHA_ENABLED: "true"
        steps:
            - uses: actions/checkout@v4
            - uses: mozilla-actions/sccache-action@v0.0.9
            - run: ./check.sh

    test-workspace:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        env:
            AZURE_MAPS_KEY: ${{ secrets.AZURE_MAPS_KEY }}
            RUSTC_WRAPPER: "sccache"
            SCCACHE_GHA_ENABLED: "true"
        steps:
            - uses: actions/checkout@v4
            - uses: mozilla-actions/sccache-action@v0.0.9
            - run: ./.github/workflows/setup-postgres.sh
            - run: ./test.sh
